baseURL = "https://kaveenranasingha2004-sentinel.github.io/scribo_site/"
languageCode = "en"
theme = "terminal"
title = "scribo ergo sum"

[[menu.main]]
  name = "about"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "posts"
  url = "/posts/"
  weight = 2

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  fullWidthTheme = false
  centerTheme = true

[params.logo]
  logoText = "scribo ergo sum"
  logoHomeLink = "/"

